### ISSUE TITLE
Blazor StateManager doesn't work with multiple wasm-interactive tabs open in a browser

### ISSUE THREAD

**Issue by Tony20221** [MarimerLLC/csla#3740]
When the Project Tracker app is running, open a new browser tab with the url of the projects list page and I get this error:

System.TimeoutException: The operation has timed out.

**Comment by rockfordlhotka** [comment]
This is against the version of CSLA in `main` (the one I forgot to push to NuGet)?

I am not seeing this on my machine.

Alternately, are you hosting the web server in a console window or in IISExpress?

**Comment by Tony20221** [comment]
The app opens two console windows.

Please push 8.0.0-R24031302 to nuget so we are comparing same versions.

**Comment by rockfordlhotka** [comment]
I fried my starlink dish, so can't push until I get home. Probably Thursday.

**Comment by rockfordlhotka** [comment]
I just pushed 24031302 (got my starlink back online)

**Comment by Tony20221** [comment]
Still same behavior.
Copy https://localhost:7164/editproject/1 in a new tab and instead of the expected page, I get a timeout exception after less than 10 seconds.

![image](https://github.com/MarimerLLC/csla/assets/99626433/cc282952-a874-4aa8-b764-540db00afbfe)


![image](https://github.com/MarimerLLC/csla/assets/99626433/2915bb68-a40c-45a0-bdb2-15f87b55cc94)

**Comment by rockfordlhotka** [comment]
Same issue as #3741

**Comment by Tony20221** [comment]
I am still getting the timeout issue after the fix from #3741. Why is this considered the same issue as  #3741?

**Comment by rockfordlhotka** [comment]
Here's what's happening - and I can use help thinking through what we think _should_ happen.

The way I am supporting state management (`LocalContext`/`ClientContext`) in Blazor 8 is by using a cookie to maintain a session id value - so a "session" will cross browser tabs.

The way I keep a "single authority" copy of state is that when the state is "moved" to a wasm client, it is considered locked on the server. It isn't unlocked until the user navigates back to a server-side page in the app.

What is happening to cause this issue, is that the user has navigated to a wasm page in _tab 1_ and so the state has moved to the wasm runtime in that tab - and is locked on the server. The user then opens _tab 2_ and attempts to use the app, so CSLA attempts to move the state from the server _to this new wasm runtime_. It can't, of course, because the state is locked on the server.

If we did allow the state to flow to _tab 2_, then there'd be no way to reconcile state changes between the two "single authority" copies of the state data.

I'm not sure how to address this. Some options come to mind:

1. Stop locking the state and let the end developer deal with the consequences of having no single authority for the state
   a. A variation on this is to not lock the state, and to not transfer the state back to the server automatically - but rather force the developer to explicitly call something like `stateManager.SaveState` after they've changed it. This would simplify the entire state management implementation in CSLA - by pushing the work onto any developer who alters values in `LocalContext` or `ClientContext`
2. Make the default for session to be "read-only", and a page would need to explicitly check out the session to alter it (this would still not prevent the issue, but would limit the issue to a few specific pages maybe?)
3. Don't allow state to be altered on a wasm client page - only server pages can change state

There may be other ideas out there - I'd love to hear them!

**Comment by kcabral817** [comment]
I like 1.a.  I think it has longevity and seems easy enough for the developers to implement, especially if we need to call StateManager.SaveState since we should be able to put that in a base class.  it would be a bonus if there was some analytics to flag the failure of implementing the strategy.

Have a nice day.

Kevin

https://rb.gy/syiuf


________________________________

**Comment by hurcane** [comment]
+1 for the 1.a technique.

**Comment by StefanOssendorf** [comment]
What about keeping the state always on the server?

**Comment by rockfordlhotka** [comment]
> What about keeping the state always on the server?

How would this work? At least without major breaking changes of the `LocalContext`/`ClientContext` API?

Right now you can do this:

```c#
var value = applicationContext.LocalContext["myvalue"] as string;
```

If this code is running on a wasm-interactive page, I think you are suggesting that it would cause a call to the server to get that specific value?

To make that happen, the operation needs to become async, and probably shouldn't be treated like a dictionary, but instead like an accessor method. More like:

```c#
var value = await applicationContext.LocalContext.GetValueAsync<string>("myvalue");
```

This isn't a terrible idea - but wow what a breaking change!!

**Comment by StefanOssendorf** [comment]
Async all the way :)
Maybe to not further postpone 8.0 use proposal 1.a..
And for 8.1/9.0 mark the indexer as obsolete that it will be replaced on 10/11 with the pure async API?

**Comment by rockfordlhotka** [comment]
fyi, I'm working on 1a and have made substantial progress.

Doing this revealed another (somewhat unrelated) issue, where the aspnetcore context manager caches the local/client context objects, so they don't properly refresh when updates are sent from a wasm page back to the server. Working on that as well.
